package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'deployment'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("deployment")) {
    params {
        remove {
            password("system.org.gradle.project.signingKey", "credentialsJSON:aebe42c4-8827-4b93-afaf-7a1bf4f46a51")
        }
        add {
            password("env.SIGNING_KEY", "credentialsJSON:aebe42c4-8827-4b93-afaf-7a1bf4f46a51")
        }
    }
}
