package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'deployment'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("deployment")) {
    params {
        remove {
            password("system.org.gradle.project.signingKey", "credentialsJSON:aebe42c4-8827-4b93-afaf-7a1bf4f46a51")
        }
        remove {
            password("system.org.gradle.project.signingPassword", "credentialsJSON:7de31dac-638d-43b6-a070-9e9d9ed3db22")
        }
        add {
            password("env.SIGNING_KEY", "credentialsJSON:a626eafb-8f0f-4152-9b21-044119c3d3da")
        }
        add {
            password("env.SIGNING_PASSWORD", "credentialsJSON:7de31dac-638d-43b6-a070-9e9d9ed3db22")
        }
    }
}
