package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.GradleBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'deployment'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("deployment")) {
    params {
        remove {
            password("system.org.gradle.project.signingKey", "credentialsJSON:aebe42c4-8827-4b93-afaf-7a1bf4f46a51")
        }
        remove {
            password("system.org.gradle.project.signingPassword", "credentialsJSON:7de31dac-638d-43b6-a070-9e9d9ed3db22")
        }
        add {
            password("env.SIGNING_KEY", "credentialsJSON:a626eafb-8f0f-4152-9b21-044119c3d3da")
        }
        add {
            password("env.SIGNING_PASSWORD", "credentialsJSON:7de31dac-638d-43b6-a070-9e9d9ed3db22")
        }
    }

    expectSteps {
        gradle {
            name = "Run checks (Debug)"

            conditions {
                equals("debug", "true")
            }
            tasks = "check"
            gradleParams = "-d --gradle-user-home .gradle-home"
        }
        gradle {
            name = "Run checks"

            conditions {
                equals("debug", "false")
            }
            tasks = "check"
            gradleParams = "--gradle-user-home .gradle-home"
        }
        gradle {
            name = "Publish Artifacts (Debug)"

            conditions {
                equals("debug", "true")
                doesNotExist("teamcity.pullRequest.number")
            }
            tasks = "publish"
            gradleParams = "-x test -d --gradle-user-home .gradle-home"
        }
        gradle {
            name = "Publish Artifacts"

            conditions {
                equals("debug", "false")
                doesNotExist("teamcity.pullRequest.number")
            }
            tasks = "publish"
            gradleParams = "-x test --gradle-user-home .gradle-home"
        }
    }
    steps {
        update<GradleBuildStep>(1) {
            clearConditions()

            conditions {
                doesNotEqual("debug", "true")
            }
        }
        update<GradleBuildStep>(3) {
            clearConditions()

            conditions {
                doesNotEqual("debug", "true")
                doesNotExist("teamcity.pullRequest.number")
            }
        }
    }
}
