package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.PullRequests
import jetbrains.buildServer.configs.kotlin.buildFeatures.pullRequests
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'qodana'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("qodana")) {
    features {
        val feature1 = find<PullRequests> {
            pullRequests {
                provider = github {
                    authType = token {
                        token = "credentialsJSON:8a0ab174-fa52-45d4-950a-05a3c36d0e63"
                    }
                    filterSourceBranch = """
                        :refs/-
                        +:refs/pull/*/head
                    """.trimIndent()
                }
            }
        }
        feature1.apply {
            provider = github {
                serverUrl = ""
                authType = token {
                    token = "credentialsJSON:6c4cf2b5-741b-420a-bd80-587c4746b827"
                }
                filterSourceBranch = """
                    :refs/-
                    +:refs/pull/*/head
                """.trimIndent()
                filterTargetBranch = ""
                filterAuthorRole = PullRequests.GitHubRoleFilter.MEMBER
            }
        }
    }
}
