package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Validation'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("Validation")
    name = "Validation"
}))

