package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.GitHubIssueTracker
import jetbrains.buildServer.configs.kotlin.projectFeatures.githubAppConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.githubIssues
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<GitHubIssueTracker> {
            githubIssues {
                id = "PROJECT_EXT_2"
                displayName = "GitHub"
                repositoryURL = "https://github.com/kordlib/kord"
                authType = accessToken {
                    accessToken = "credentialsJSON:6c4cf2b5-741b-420a-bd80-587c4746b827"
                }
            }
        }
        feature1.apply {
        }
        add {
            githubAppConnection {
                id = "PROJECT_EXT_3"
                displayName = "GitHub App"
                appId = "809339"
                clientId = "Iv1.d49f98e64cf54c69"
                clientSecret = "credentialsJSON:1a89764e-1763-4207-a749-d67a9f869d84"
                privateKey = "credentialsJSON:665df066-e1f4-424a-be5b-2224a68ea837"
                webhookSecret = "credentialsJSON:9c73ba09-65a9-487c-a0d5-acbbb1b693b5"
                ownerUrl = "https://github.com/kordlib"
            }
        }
    }
}
