package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.GitHubIssueTracker
import jetbrains.buildServer.configs.kotlin.projectFeatures.githubIssues
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<GitHubIssueTracker> {
            githubIssues {
                id = "PROJECT_EXT_2"
                displayName = "GitHub"
                repositoryURL = "https://github.com/kordlib/kord"
                authType = accessToken {
                    accessToken = "credentialsJSON:8a0ab174-fa52-45d4-950a-05a3c36d0e63"
                }
            }
        }
        feature1.apply {
        }
    }
}
