name: Bug Report
description: Something is broken or doesn't work as expected!
title: '[BUG]: '
labels: bug

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue on the tracker?
      description: Please search to see if an issue report already exists for the bug you encountered
      options:
        - label: I have searched the issue tracker
          required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A description of what is happening
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A description of what you expected to happen
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction steps
      description: Steps to reproduce the behavior
      placeholder: |
        1. In this environment
        1. With this setup
        1. Run '...'
        1. See error/unexpected behavior
    validations:
      required: false
  - type: textarea
    attributes:
      label: Code snippet
      description: If you can, please provide a snippet of the code that produces this error
      placeholder: This area will format the code to Kotlin, no need for backticks!
      renderer: kotlin
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        example:
          - **Kord Version**: 0.17.0
          - **Kotlin Version**: 2.3.0
          - **Gradle Version**: 9.3.0
      value: |
        - Kord Version:
        - Kotlin Version:
        - Gradle Version:
      renderer: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more information about the issue you're encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and dragging files in.
    validations:
      required: false
