# This workflow will validate the checksums of Gradle Wrapper JAR files

name: Gradle Wrapper Validation

on: [ push, pull_request ]

jobs:
  validation:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
